apiVersion: v1
kind: Service
metadata:
  name: active-app
spec:
  selector:
    app: blue-green-app
  ports:
    - protocol: TCP
      port: 80       # The port your app will be accessed internally
      targetPort: 80 # The port your app is listening on internally
  type: NodePort # Exposes the service using NodePort, without specifying a nodePort

---
apiVersion: v1
kind: Service
metadata:
  name: preview-app
spec:
  selector:
    app: blue-green-app
  ports:
    - protocol: TCP
      port: 80       # The port your app will be accessed internally
      targetPort: 80 # The port your app is listening on internally
  type: NodePort # Exposes the service using NodePort, without specifying a nodePort

