apiVersion: v1
kind: Service
metadata:
  name: active-app
spec:
  selector:
    app: blue-green-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: preview-app
spec:
  selector:
    app: blue-green-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
